[package]
name = "oxid-web"
description = "oxid front end, Leptos CSR"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
oxid-shared.workspace = true

console_error_panic_hook.workspace = true
gloo-net.workspace = true
gloo-storage.workspace = true
js-sys.workspace = true
leptos = { workspace = true, features = ["csr"] }
serde.workspace = true
web-sys.workspace = true

[lints]
workspace = true
